site_name: Strip Number Prefix Demo
site_description: Demonstration of the vexy-mkdocs-strip-number-prefix plugin
site_url: https://example.com/
site_author: Documentation Team

# Documentation source
docs_dir: src_docs
site_dir: docs

# Theme configuration
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search
  - strip-number-prefix:
      pattern: '^\d+--'
      strict: false
      strip_links: true
      strip_nav_titles: true
      verbose: true

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Navigation
# Let MkDocs discover the structure automatically
# The plugin will strip the prefixes from the URLs

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vexyart/vexy-mkdocs-strip-number-prefix